services:
  - type: web
    name: jewelrymakers
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      export FLASK_APP=app.py &&
      export FLASK_ENV=production &&
      flask db upgrade &&
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: jewelrymakers_db
          property: connectionString

databases:
  - name: jewelrymakers_db
    plan: free 